version: '3.7'

services:
  ssh-to-docker-host:
    image: jnovack/autossh
    container_name: autossh-ssh-to-docker-host
    environment:
      - SSH_HOSTUSER=SSHuser
      - SSH_HOSTNAME=raven.it108.org
      - SSH_TUNNEL_REMOTE=2222
      - SSH_TUNNEL_HOST=172.28.1.3
      - SSH_TUNNEL_LOCAL=80
      - SSH_STRICT_HOST_IP_CHECK=false
      - SSH_KEY_FILE=/tun/id_rsa
    restart: always
    volumes:
      - ./tunnel/:/tun/
    networks:
        ad_net:
            ipv4_address: 172.28.1.1
    dns:
      - 8.8.8.8
      - 1.1.1.1


  ADhelper:
    image: ad
    container_name: ad
    ports: 
        - 8080:80
    environment:
        - DOMAIN_PATH=${AD_DOMAIN_PATH}
        - DOMAIN_NAME=${AD_DOMAIN_NAME}
        - AUTH_KEY=${AD_AUTH_KEY}
        - MASTER_KEY=${AD_MASTER_KEY}
        - ADMIN_USERNAME=${AD_ADMIN_USERNAME}
        - ADMIN_PASSWORD=${AD_ADMIN_PASSWORD}
    restart: always
    networks:
        ad_net:
            ipv4_address: 172.28.1.3
    dns:
      - 8.8.8.8
      - 1.1.1.1

      
networks:
    ad_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16