version: '3.7'

services:

    ADhelper:
        image: iorp/achieve-adagent:1809
        container_name: achieve-adagent
        ports: 
            - 8080:80
        environment:
            - DOMAIN_PATH=${AD_DOMAIN_PATH}
            - DOMAIN_NAME=${AD_DOMAIN_NAME}
            - AUTH_KEY=${AD_AUTH_KEY}
            - SERVER_ADDRESS=${AD_SERVER_ADDRESS}
            - EDGE_ADDRESS=${AD_EDGE_ADDRESS}
            - MASTER_KEY=${AD_MASTER_KEY}
            - ADMIN_USERNAME=${AD_ADMIN_USERNAME}
            - ADMIN_PASSWORD=${AD_ADMIN_PASSWORD}
        restart: always
        networks:
            adagent_net:
                ipv4_address: 172.29.1.1
        dns:
        - 8.8.8.8
        - 1.1.1.1

networks:
    adagent_net:
        ipam:
            driver: default
            config:
                - subnet: 172.29.1.0/16
